version: '3.8'

services:
  todolist_pg:
    container_name: todolist_pg
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./docker/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql # will setup dev database adonis_app for us
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  postgres_volume:
